name: Deploy via SFTP
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - name: Install npm dependencies
        run: npm install
        
      - name: Run build task
        run: npm run build --if-present

      - name: Run server install script
        run: |
          cd server
          bash install-composer.sh
        shell: bash

      - name: Copy server to dist
        run: cp -r server dist/server

      - name: Deploy files via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          # SFTP credentials
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          user: ${{ secrets.SFTP_USER }}
          pass: ${{ secrets.SFTP_PASS }}
          # lftp settings
          onlyNewer: true
          settings: 'sftp:auto-confirm=yes'
          # Mirror command options
          localDir: 'dist'  # Set localDir to 'dist'
          remoteDir: ${{ secrets.SFTP_DIR }}
          reverse: true
          ignoreFile: '.lftp_ignore'
          options: '--verbose --delete'
